.TH BAKU "1" "April 2019" "baku " "User Commands"
.SH NAME
baku \- create timestamped backup copies of files and directories
.SH SYNOPSIS
.B baku
[\fI\,-h\/\fR] [\fI\,-V\/\fR] [\fI\,-v\/\fR] [\fI\,-d\/\fR] [\fI\,-t TARGET\/\fR] [\fI\,-i ISOFORMAT\/\fR] [\fI\,-f FORMAT\/\fR] [\fI\,-s SUFFIX\/\fR] \fI\,SRC\/\fR
.SH DESCRIPTION
Baku is a tool to create backup copies of files and directories with a timestamp
appended to their name.
It uses 'cp' as backend and creates timestamps with the 'date' function.
.TP
\fB\-h\fR
Display usage of baku.
.TP
\fB\-V\fR
Version. Print version number and quit.
.TP
\fB\-v\fR
Verbose. Pass '\-v' option to 'cp'.
.TP
\fB\-d\fR
Dry\-run. The cp command will only be echoed instead of executed.
.TP
\fB\-t\fR
Specify a directory where to move the backups to.
.TP
\fB\-i\fR
Specify ISO time format passed to 'date --iso-8601=seconds'. Default is 'seconds'.
.br
All valid options are 'hours', 'minutes', 'seconds' and 'ns'.
.TP
\fB\-f\fR
Specify time format passed to date, e.g., '%Y%m%d-%H:%M:%S'
.br
Overrules '-i' option.
.TP
\fB\-s\fR
Specify a different suffix for target, e.g., '.backup'
.br
Overrules '-f' and '-i' option.
.PP
.SH "USAGE"

.PP 
To create an ISO-8601 timestamped copy of 'testfile', execute:
.PP 
.RS
\f(CWbaku testfile\fP
.RE

.PP 
This creates the file 'testfile.2019-04-07T21:14:26+02:00' in the same
directory.
.PP 
.SH "EXIT VALUES"

.PP 
.IP "\fB0\fP"
Success
.IP "\fB1\fP"
Syntax or usage error
.IP "\fB2\fP"
Syntax error in format string passed to 'date'.
